---
- hosts: appserver
  become: yes
  tasks:
   - name: update package
     apt:
       update_cache: yes
   - name: install tomcat
     apt:
       name: tomcat7
       state: present
   - name: start tomcat service
     service:
       name: tomcat7
       state: start
