---
- hosts: webserver
  become: yes
  tasks:
  - name: update package for debian
    apt:
      update_cache: yes
    when: ansible_os_family == "Debian"
  - name: install apache for Debian
    apt:
      name: "{{pack_name}}"
      state: present
    notify:
    - Restart Apache
    when: ansible_os_family == "Debian"
  - name: install apache for Redhat
    yum:
      name: "{{ pack_name }}"
      state: present
    notify:
    - Restart Apache
    when: ansible_os_family == "Redhat"

    handlers:
    - name: Restart Apache
      service:
        name: "{{ pack_name }}"
        state: restarted